# Generated by Django 3.1.3 on 2021-05-16 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_manage', '0003_auto_20210516_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('url', models.TextField(verbose_name='URL')),
                ('header', models.TextField(null=True, verbose_name='请求头')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=100, verbose_name='请求方式')),
                ('request_type', models.CharField(choices=[('FORM-DATA', 'FORM-DATA'), ('JSON', 'JSON')], default='FORM-DATA', max_length=100, verbose_name='请求类型')),
                ('result', models.TextField(null=True, verbose_name='响应结果')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_manage.module')),
            ],
            options={
                'db_table': 'apicase',
            },
        ),
    ]
