# Generated by Django 3.1.3 on 2021-03-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
